# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/euris/Developers/crystal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/euris/Developers/crystal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/euris/Developers/crystal/CMakeFiles /home/euris/Developers/crystal//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/euris/Developers/crystal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named slimlock

# Build rule for target.
slimlock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slimlock
.PHONY : slimlock

# fast build rule for target.
slimlock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slimlock.dir/build.make CMakeFiles/slimlock.dir/build
.PHONY : slimlock/fast

#=============================================================================
# Target rules for targets named slim

# Build rule for target.
slim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slim
.PHONY : slim

# fast build rule for target.
slim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/build
.PHONY : slim/fast

#=============================================================================
# Target rules for targets named libslim

# Build rule for target.
libslim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libslim
.PHONY : libslim

# fast build rule for target.
libslim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/build
.PHONY : libslim/fast

PAM.o: PAM.cpp.o
.PHONY : PAM.o

# target to build an object file
PAM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/PAM.cpp.o
.PHONY : PAM.cpp.o

PAM.i: PAM.cpp.i
.PHONY : PAM.i

# target to preprocess a source file
PAM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/PAM.cpp.i
.PHONY : PAM.cpp.i

PAM.s: PAM.cpp.s
.PHONY : PAM.s

# target to generate assembly for a file
PAM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/PAM.cpp.s
.PHONY : PAM.cpp.s

app.o: app.cpp.o
.PHONY : app.o

# target to build an object file
app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/app.cpp.o
.PHONY : app.cpp.o

app.i: app.cpp.i
.PHONY : app.i

# target to preprocess a source file
app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/app.cpp.i
.PHONY : app.cpp.i

app.s: app.cpp.s
.PHONY : app.s

# target to generate assembly for a file
app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/app.cpp.s
.PHONY : app.cpp.s

cfg.o: cfg.cpp.o
.PHONY : cfg.o

# target to build an object file
cfg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/cfg.cpp.o
.PHONY : cfg.cpp.o

cfg.i: cfg.cpp.i
.PHONY : cfg.i

# target to preprocess a source file
cfg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/cfg.cpp.i
.PHONY : cfg.cpp.i

cfg.s: cfg.cpp.s
.PHONY : cfg.s

# target to generate assembly for a file
cfg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/cfg.cpp.s
.PHONY : cfg.cpp.s

image.o: image.cpp.o
.PHONY : image.o

# target to build an object file
image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/image.cpp.o
.PHONY : image.cpp.o

image.i: image.cpp.i
.PHONY : image.i

# target to preprocess a source file
image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/image.cpp.i
.PHONY : image.cpp.i

image.s: image.cpp.s
.PHONY : image.s

# target to generate assembly for a file
image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/image.cpp.s
.PHONY : image.cpp.s

jpeg.o: jpeg.c.o
.PHONY : jpeg.o

# target to build an object file
jpeg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/jpeg.c.o
.PHONY : jpeg.c.o

jpeg.i: jpeg.c.i
.PHONY : jpeg.i

# target to preprocess a source file
jpeg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/jpeg.c.i
.PHONY : jpeg.c.i

jpeg.s: jpeg.c.s
.PHONY : jpeg.s

# target to generate assembly for a file
jpeg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/jpeg.c.s
.PHONY : jpeg.c.s

log.o: log.cpp.o
.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i
.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s
.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/log.cpp.s
.PHONY : log.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/main.cpp.s
.PHONY : main.cpp.s

numlock.o: numlock.cpp.o
.PHONY : numlock.o

# target to build an object file
numlock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/numlock.cpp.o
.PHONY : numlock.cpp.o

numlock.i: numlock.cpp.i
.PHONY : numlock.i

# target to preprocess a source file
numlock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/numlock.cpp.i
.PHONY : numlock.cpp.i

numlock.s: numlock.cpp.s
.PHONY : numlock.s

# target to generate assembly for a file
numlock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/numlock.cpp.s
.PHONY : numlock.cpp.s

panel.o: panel.cpp.o
.PHONY : panel.o

# target to build an object file
panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/panel.cpp.o
.PHONY : panel.cpp.o

panel.i: panel.cpp.i
.PHONY : panel.i

# target to preprocess a source file
panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/panel.cpp.i
.PHONY : panel.cpp.i

panel.s: panel.cpp.s
.PHONY : panel.s

# target to generate assembly for a file
panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/panel.cpp.s
.PHONY : panel.cpp.s

png.o: png.c.o
.PHONY : png.o

# target to build an object file
png.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/png.c.o
.PHONY : png.c.o

png.i: png.c.i
.PHONY : png.i

# target to preprocess a source file
png.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/png.c.i
.PHONY : png.c.i

png.s: png.c.s
.PHONY : png.s

# target to generate assembly for a file
png.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/png.c.s
.PHONY : png.c.s

slimlock.o: slimlock.cpp.o
.PHONY : slimlock.o

# target to build an object file
slimlock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slimlock.dir/build.make CMakeFiles/slimlock.dir/slimlock.cpp.o
.PHONY : slimlock.cpp.o

slimlock.i: slimlock.cpp.i
.PHONY : slimlock.i

# target to preprocess a source file
slimlock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slimlock.dir/build.make CMakeFiles/slimlock.dir/slimlock.cpp.i
.PHONY : slimlock.cpp.i

slimlock.s: slimlock.cpp.s
.PHONY : slimlock.s

# target to generate assembly for a file
slimlock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slimlock.dir/build.make CMakeFiles/slimlock.dir/slimlock.cpp.s
.PHONY : slimlock.cpp.s

switchuser.o: switchuser.cpp.o
.PHONY : switchuser.o

# target to build an object file
switchuser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/switchuser.cpp.o
.PHONY : switchuser.cpp.o

switchuser.i: switchuser.cpp.i
.PHONY : switchuser.i

# target to preprocess a source file
switchuser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/switchuser.cpp.i
.PHONY : switchuser.cpp.i

switchuser.s: switchuser.cpp.s
.PHONY : switchuser.s

# target to generate assembly for a file
switchuser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/switchuser.cpp.s
.PHONY : switchuser.cpp.s

util.o: util.cpp.o
.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i
.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s
.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslim.dir/build.make CMakeFiles/libslim.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... libslim"
	@echo "... slim"
	@echo "... slimlock"
	@echo "... PAM.o"
	@echo "... PAM.i"
	@echo "... PAM.s"
	@echo "... app.o"
	@echo "... app.i"
	@echo "... app.s"
	@echo "... cfg.o"
	@echo "... cfg.i"
	@echo "... cfg.s"
	@echo "... image.o"
	@echo "... image.i"
	@echo "... image.s"
	@echo "... jpeg.o"
	@echo "... jpeg.i"
	@echo "... jpeg.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... numlock.o"
	@echo "... numlock.i"
	@echo "... numlock.s"
	@echo "... panel.o"
	@echo "... panel.i"
	@echo "... panel.s"
	@echo "... png.o"
	@echo "... png.i"
	@echo "... png.s"
	@echo "... slimlock.o"
	@echo "... slimlock.i"
	@echo "... slimlock.s"
	@echo "... switchuser.o"
	@echo "... switchuser.i"
	@echo "... switchuser.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

